### ISSUE TITLE
Request: Cart Expired after 10 minutes of message.

### ISSUE THREAD

**Issue by ShaneAbara** [fraserdale/freeCarts#30]
Can you put a message "Cart Expired" once a message reaches 10 minutes so that people won't be able to claim it since the HMAC is already burned.

**Comment by fraserdale** [comment]
hmmm, yeah will do that later on, sorry couldn't update before today.

**Comment by ShaneAbara** [comment]
I badly needed to have carts change when it's already expired or after 10 minutes.

**Comment by ShaneAbara** [comment]
Fixed it by myself! Thank you @fraserdale

**Comment by fraserdale** [comment]
sorry i couldn't update for you in time.

**Comment by fraserdale** [comment]
https://github.com/fraserdale/freeCarts/commit/34cfcdf27790d36e9c87fa76db07563165b29522
