### ISSUE TITLE
Request: Add Support for BalkoBot

### ISSUE THREAD

**Issue by ignok99** [fraserdale/freeCarts#31]

**Comment by fraserdale** [comment]
If you can help me out with a picture of the embed. Or lend me the key i can look into it

**Comment by ignok99** [comment]
size = (e.fields)[2]['value']
                email = (e.fields)[0]['value']
                pass = (e.fields)[1]['value']
                loginURL = e.url
                img = e.thumbnail.url
                sku = (e.fields)[4]['value']

**Comment by ignok99** [comment]
e.footer.text === 'Balkobot'

**Comment by fraserdale** [comment]
implemented
