### ISSUE TITLE
Carts Dont Send

### ISSUE THREAD

**Issue by hypemonitor** [fraserdale/freeCarts#34]
I had the previous version and when i updated the carts dont send to user anymore when they click on the cart emoji. Everything else works fine. 

Bot: : Latchkey

**Comment by nickydnyc123** [comment]
Having the same problem with latckey.

**Comment by nickydnyc123** [comment]
Having the same issue

**Comment by fraserdale** [comment]
Please refer closely to the youtube video in the Readme
