### ISSUE TITLE
Bot doesnt load image and Login URL

### ISSUE THREAD

**Issue by hypemonitor** [fraserdale/freeCarts#38]
When users click on the cart emoji, it doesnt send them a log in URL or load the picture
<img width="449" alt="Screen Shot 2019-04-21 at 1 29 37 PM" src="https://user-images.githubusercontent.com/42697536/56475177-b723c900-6439-11e9-8a1f-8dba8f987b4a.png">

**Comment by connorlurring** [comment]
What bot was this with?

**Comment by connorlurring** [comment]
This is related to #34
