### ISSUE TITLE
login details incorrect

### ISSUE THREAD

**Issue by housewithbricks** [fraserdale/freeCarts#40]
after starting the program and filling in all issue and double and triple checking still get this issue

**Comment by connorlurring** [comment]
Is this issue about the login details for discord, or the login details for the Adidas accounts?

**Comment by housewithbricks** [comment]
yes, the login details for discord

**Comment by connorlurring** [comment]
Following the instruction in the readme exactly will allow for the correct setup.

When attempting to add the bot login details to the program, make sure you are using the bot token and not the client secret for your application.
