### ISSUE TITLE
Add Support for Kodai

### ISSUE THREAD

**Issue by JamesLutzke** [fraserdale/freeCarts#42]
![Kodai Cart 1](https://user-images.githubusercontent.com/26281365/58525555-28be0800-819a-11e9-8cdd-f95fc528a039.PNG)
![Kodai Cart 2](https://user-images.githubusercontent.com/26281365/58525556-29569e80-819a-11e9-8f69-c28e7aa60484.PNG)

**Comment by fraserdale** [comment]
Thank you

**Comment by fraserdale** [comment]
https://github.com/fraserdale/freeCarts/commit/d451e0599e5ded021b85f34f7d11ddc90cb1e8e9
