### ISSUE TITLE
No response 

### ISSUE THREAD

**Issue by MrBigthicc** [fraserdale/freeCarts#43]
Tried to install the bot tried 3x and no response from the bot 

audited 520 packages in 1.46s
found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

i fix it then
npm start

enter all my info correctly 

![image](https://user-images.githubusercontent.com/51213938/58663819-48b90d00-82fb-11e9-9a07-1e101137ba7b.png)

It seems its not reaching anything?

**Comment by resellfeed** [comment]
I have the same issue, I believe it has something to do with the config.json file missing?

**Comment by Trying2work** [comment]
i am also having the same problem

**Comment by simon-kim** [comment]
The save function isn't firing. I recreated the config.json file and I can start the bot now, just getting incorrect login details. Still poking around, will let you know if I find anything.

**Comment by giveme11us** [comment]
> The save function isn't firing. I recreated the config.json file and I can start the bot now. Still poking around, will let you know if I find anything.

can u please share the config.json file without info?
@simon-kim

**Comment by saigorupati** [comment]
> > The save function isn't firing. I recreated the config.json file and I can start the bot now. Still poking around, will let you know if I find anything.
> 
> can u please share the config.json file without info?
> @simon-kim

Can you please share this, would be very much appreciated! @simon-kim

**Comment by jacksondevoe** [comment]
{
"server": "serverid",
"privateChannel": "privateid",
"publicChannel": "publicid",
"botToken": "bottoken",
"quantityCart": "1",
"after10": "true",
"cooldown": "5",
"deleteAfterReact": "true"
}

this is the .json file.

still won't work for me though, says my info is wrong, idk why

**Comment by fraserdale** [comment]
Pull latest version
