### ISSUE TITLE
AdiSplash Cart Issue Fix

### ISSUE THREAD

**Issue by OfficiallyAnti** [fraserdale/freeCarts#46]
In adapters.js the const sku is defined below the img const, which uses this sku, causing a "ReferenceError: sku is not defined". Please move the assignment of the sku const over the assignment of the img const.
![image](https://user-images.githubusercontent.com/39014772/58832749-ec822000-864f-11e9-9070-c75b35e4ef38.png)

**Comment by fraserdale** [comment]
Pull latest version
