### ISSUE TITLE
config.json setup fix

### ISSUE THREAD

**Issue by madebyerick** [fraserdale/freeCarts#48]
make a new json file and copy the things below replace with your info 

{
    "server": "serverid",
    "privateChannel": "privateid",
    "publicChannel": "publicid",
    "botToken": "bottoken",
    "quantityCart": "1",
    "after10": "true",
    "cooldown": "5",
    "deleteAfterReact": "true"
}

**Comment by fraserdale** [comment]
Pull latest version
