### ISSUE TITLE
config.json won't turn bot on

### ISSUE THREAD

**Issue by jacksondevoe** [fraserdale/freeCarts#49]
I keep clicking start after entering all my info on the left, but it won't turn on/start the bot inside my discord.

**Comment by saigorupati** [comment]
having the same issue as well

**Comment by jacksondevoe** [comment]
I tried the suggestion of making a new file with my info in it, but when I try to start the bot it says my info is wrong

**Comment by saigorupati** [comment]
The new commit makes it work for me, just redownload the new zip file @jacksondevoe

**Comment by jacksondevoe** [comment]
@saigorupati so just completely redo the entire thing and add the new .json file?

**Comment by saigorupati** [comment]
the new zip file has the config.json file included so you dont need to do anything just do the npm i and then nmp start and fill in the info

**Comment by jacksondevoe** [comment]
@saigorupati ok I redid it and the bot is online but when I try to send carts they only appear in the private channel. No pop up in the main channel with an emoji to react to

**Comment by jacksondevoe** [comment]
nevermind it works!!

**Comment by Trying2work** [comment]
> nevermind it works!!

how did you get it to work? im having the same issue not sure why

**Comment by fraserdale** [comment]
Pull latest version
