### ISSUE TITLE
Kodai Error

### ISSUE THREAD

**Issue by JamesLutzke** [fraserdale/freeCarts#57]
When a cart is sent to the server, I get the following error and the cart is not sent to the public channel.
![cart free carts](https://user-images.githubusercontent.com/26281365/59552442-f3b10400-8f54-11e9-8e52-000f75f94a54.PNG)
![logs free carts](https://user-images.githubusercontent.com/26281365/59552446-f9a6e500-8f54-11e9-9f4f-d4f92fb7c010.PNG)

**Comment by fraserdale** [comment]
Duplicate fixed https://github.com/fraserdale/freeCarts/commit/1cca760ae3143d24bca4e59a35611fc281c8ac60
